---
title: "HBoV-1 Persistence Modeling"
date: "`r format(Sys.time(),'%B, %d, %Y')`"
output:
  rmdformats::material:
    highlight: kate
    code_folding: hide
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# R Packages Used

```{r library loading}
library(lubridate)    # time and date functions
library(gridExtra)    # grid.arrange
library(xts)          # time-series objects and functions
library(knitr)        
library(Rmisc)        
library(visreg)       # visualize regressions
library(ggthemes)     # theme_tufte, theme_bw, etc.
library(gridExtra)    # arrange ggplot grobs
library(RColorBrewer) # plotting colors
library(lattice)      # versatile plotting functions
library(magrittr)     # extra pipelines/infix operators (%<>%)
library(reshape2)     # melt and cast data, i.e. wide to long, long to wide
library(tidyverse)    # everything, including ggplot, dplyr, etc.
library(caret)        # model building and testing
```

# Load Data

```{r}
setwd("S:/MartinEpi/Analysis/Bocavirus Persistence Modeling/Rdata/")
dem.clin.dat <- readRDS("dem_clin_dat.rds")
diaries <- readRDS("diaries.rds")
diary.pos <- readRDS("diary_pos.rds")
id <- readRDS("pos_id.rds")
main <- readRDS("main.rds")
main.long <- readRDS("main_long.rds")
main.pos <- readRDS("main_pos.rds")
pcr.by.week <- readRDS("pcr_by_week.rds")
results.dob <- readRDS("results_dob.rds")
season.decomp <- readRDS("season_decomp.rds")
test.results.pos <- readRDS("test_results_pos.rds")
durations <- readRDS("durations.rds")
```

# Explore Data

```{r}
dim(dem.clin.dat)
```


